### ISSUE TITLE
Related project API Extractor

### ISSUE THREAD

**Issue by octogonz** [nomaed/dts-builder#11]
@nomaed FYI we've been working on a tool [API Extractor](https://api-extractor.com/pages/basics/intro/) that seems to have some overlap with the goals of **dts-builder**.  It might be interesting to compare the features and goals of the two projects, and see if anything can be shared between them.

**Comment by nomaed** [comment]
API Extractor looks interesting!

The dts-builder project was a small tool I created just to merge multiple definition files from the compilation of a library into a single file. I am not developing the project anymore (I'd fix bugs if any were reported, of course). 

If there's anything that you think can be useful, feel free to take and adapt for your needs :)
