### ISSUE TITLE
Option to avoid external namespace wrapper

### ISSUE THREAD

**Issue by rbarriuso** [nomaed/dts-builder#2]
Currently the generated d.ts file is wrapped by a general namespace which takes the name from the "name" parameter of the configuration passed to "generateBundles()".

It would be good to have a flag to avoid generating that external namespace, in case your library already declares the desired namespaces itslef.

**Comment by nomaed** [comment]
Looking into it.

How are the sources organized, and how are you using the unified d.ts file?
Is it multiple files that all have their content wrapper in `export namespace foobar { ... }`?
Are you importing definitions from d.ts or are you using the result in ambient context using `/// reference`?

I am trying to see what cleanup or rewrites needs to happen.
If using `export namespace` then the resulting d.ts files get `export declare namespace`.
However, if the namespaces aren't exported, the d.ts files still have the namespaces and all the exported content and then they can be used as ambient modules.

**Comment by rbarriuso** [comment]
Actually the source files have a grouping criterion (i.e. directories) different from the classes grouping into namespaces.

For example, the following directory tree:
```
src
├── core
├── dynamic-variables
│   ├── dynamic-variables-rg
│   └── dynamic-variables-sc
├── models
├── persistence
└── resource-gallery
    └── resource-gallery-tabs
```

Has several classes per directory, but only two namespaces, say `namespace MyCore {...` and `namespace MyCommon {...`.

For our use case the only thing that prevents the `dts-builder` output file to work straight away is the outer namespace which wraps everything (the one which takes the name from the `name` configuration parameter)

Thanks!

**Comment by nomaed** [comment]
Other than wrapping everything in a namespace, I also strip the `declare` and etc.
Also, there is a difference in how d.ts files are generated by `tsc` when files use namespaces and when they don't.

I added a branch to test this:
https://github.com/nomaed/dts-builder/tree/no-namespace-wrapper

It has a new flag in the configuration: `wrap`. 
Can you please set it to `false` and see if it works for you?

**Comment by rbarriuso** [comment]
Works great!! Thanks
