### ISSUE TITLE
Library name converted to lower case

### ISSUE THREAD

**Issue by jamesots** [nomaed/dts-builder#3]
When I configure dts-builder with a name of 'Main', the module and namespace which are created are both called 'main' instead. This is a problem, as I'm trying to gradually convert code from being namespaced to being modular, so I need to be able to keep the same namespace name.

**Comment by nomaed** [comment]
@jamesots I made a change so that if you module name is a single word, the name remains unchanged. I think that this should solve your use case.
Please let me know if it's good.

Change https://github.com/nomaed/dts-builder/commit/e7f9ea2c2616ee2d8e17d8cde2ce7b394fb4447b

**Comment by jamesots** [comment]
@nomaed That's perfect. Thank you.
