### ISSUE TITLE
imports from external libraries are not emitted

### ISSUE THREAD

**Issue by ajafff** [nomaed/dts-builder#6]
My library exports types that use types from external libraries. For example
```ts
import {OnChanges} from '@angular/core';
export class MyComponent implements OnChanges {}
```

The bundled declaration file does not contain the import. That results in type errors or implicit any.
```ts
export class MyComponent implements OnChanges {}
                                    ~~~~~~~~~ Cannot find name 'OnChanges'
```

**Comment by nomaed** [comment]
That's correct. This is the intended behavior.
The idea is to allow exporting of an internal library. External libraries should be imported by the application that's using them.

There's no reason for "myLibrary" to have interfaces that belong to "angular" or any 3rd party.

**Comment by nomaed** [comment]
You can use the `externals` property in the configuration if you want to add additional `d.ts` files to be referenced by the main library, if it helps.
